### ISSUE TITLE
Style : avoid showing a scrollbar if the label's text does not fit 

### ISSUE THREAD

**Issue by Romainpetit** [ChuckJHardy/ColorTitlesTrello#14]
From a comment on the [Chrome Extension page](https://chrome.google.com/webstore/detail/card-color-titles-for-tre/hpmobkglehhleflhaefmfajhbdnjmgim/reviews?utm_source=chrome-ntp-icon) by [Lourens Rhijnsburger](https://plus.google.com/+LourensRhijnsburger)

>  Also when too small column I get a scrollbar, can we remove that to save some screen realestate?

Showing the labels on two lines would take too much real estate for a questionable use. 
I'd guess the best option is to remove the scrollbar:

```
.list-card-labels {
    overflow: hidden;
}
```

Example of the issue happening 
![image](https://cloud.githubusercontent.com/assets/632197/24359573/0a435a7a-1305-11e7-8794-5c87e1ff8cb5.png)

Expected 
![image](https://cloud.githubusercontent.com/assets/632197/24359445/af32d750-1304-11e7-9bfd-a538844e236a.png)

**Comment by ChuckJHardyGA** [comment]
Could you submit a PR please @Romainpetit

**Comment by Romainpetit** [comment]
Sure, coming soon!

**Comment by Romainpetit** [comment]
Closing this for the moment as Trello released (finally !) a similar built-in solution that makes this extension stop to work for the moment.
